# Generated by Django 5.0.7 on 2024-08-11 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(max_length=220)),
                ('camp_status', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pin_code', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=20, default=None, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=20, default=None, max_digits=30)),
                ('camp_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_approved_user', to='accounts.customuser')),
                ('camp_create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_create_user', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=220)),
                ('listed_date', models.DateField(auto_now_add=True)),
                ('required_date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('quantity_type', models.CharField(choices=[('kg', 'Kg'), ('gram', 'Gram'), ('nos', 'Nos'), ('litre', 'Litre'), ('small', 'Small'), ('large', 'Large')], max_length=20)),
                ('category', models.CharField(choices=[('medicine', 'Medicine'), ('cloth', 'Cloth'), ('food', 'Food'), ('stationary', 'Stationary')], max_length=20)),
                ('urgent', models.BooleanField(default=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.campdetails')),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Received_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_item_name', models.CharField(max_length=220)),
                ('quantity', models.IntegerField()),
                ('quantity_type', models.CharField(max_length=20)),
                ('received_date', models.DateField()),
                ('receive_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_approved_admin', to='accounts.customuser')),
                ('received_camp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_received_camp', to='products.campdetails')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.customuser')),
            ],
        ),
    ]
